### ISSUE TITLE
Average rating not update when user rating.

### ISSUE THREAD

**Issue by vanloc0301** [fancyecommerce/yii2_fecshop#10]
I. Average Rating.

I clone new account to test function `Add Review` in Desktop version.
When user review, the values of `average rating` should be updated.

Test link: [https://fecshop.appfront.fancyecommerce.com/reindeer-pattern-glitter-christmas-dress-86519596](https://fecshop.appfront.fancyecommerce.com/reindeer-pattern-glitter-christmas-dress-86519596)

I can't see `average rating` is not update.

II. Admin `Fecshop`

Can you provider screenshot of Admin `Fecshop`?

I can't install yii2_fecshop because of language barriers, but I feel your project very interesting.

Have you plan to do `fecshop` like Magento, you need to add more function in Admin.

Please add your roadmap and checked in a feature was completed.

III. Suggestions (almost in `appfront`, because I don't access to `appadmin`)

1. Add button `Add To Card`.

I think you should add button `Add To Cart` in the main layout of the webpage. Like:

![capture](https://cloud.githubusercontent.com/assets/4168981/26221181/d1ff25f4-3c3f-11e7-9fb2-51bd0724d722.PNG)

This feature will easy for end user. Quick add to the card and continues shopping, don't need to go to details of the product.

2. Hover product shows more information about that products.

3. Keep `.top_nav` (don't hide) when scroll.

I think think this easy for end user. When user click adds to the card with Ajax will update in `.mycart`. Customer know products are added in their card(include number item in the cart), continues to surf your shop.
The height of your `.top_nav` is short. So, it doesn't affect to a user experience.

Thanks.

**Comment by fancyecommerce** [comment]
1.admin language is chinese  ，   test  demo:
front:
http://demo.appfront.fecshop.com/
admin:
http://demo.appadmin.fecshop.com/
user：demo
pass：demo123

2. review should accept in admin by service people
3. now, Fecshop project only me in development , The project is still in continuous development, pc and background has been developed to complete, and now do wap .
And other development is completed, will find someone to help write an English document, but the text inside the program, are Chinese comments,
The workload is still quite large
4. Add a shopping cart to choose a lot of custom parameters, this feature will be added in the future
thank you/

**Comment by fancyecommerce** [comment]
admin   accept review  ， you kan see   product review  rate  is changed:
https://fecshop.appfront.fancyecommerce.com/catalog/reviewproduct/lists?spu=men0002&_id=57d62e84f656f2b57ddf9def

**Comment by vanloc0301** [comment]
That's great @fancyecommerce
