### ISSUE TITLE
Have admin panel in Fecshop?

### ISSUE THREAD

**Issue by vanloc0301** [fancyecommerce/yii2_fecshop#4]
1. Admin:

I tried with: 

https://fecshop.appfront.fancyecommerce.com/admin

Seem not working.

2. Is Fecshop support multiple languages?

Thanks @fancyecommerce

**Comment by fancyecommerce** [comment]
@vanloc0301 
1.admin url:https://fecshop.appadmin.fancyecommerce.com
2.frontend, support mutil language,you can visit https://fecshop.appfront.fancyecommerce.com
,in left top,you can change language

**Comment by vanloc0301** [comment]
@fancyecommerce Have some issues with your admin page.

> yii\base\InvalidValueException
> 
> this domain is not config in store component

**Comment by fancyecommerce** [comment]
@vanloc0301   I opened https, now you can access the background : https://fecshop.appadmin.fancyecommerce.com
Background account and password is not open, hope to understand

**Comment by fancyecommerce** [comment]
@vanloc0301  Which country is your country? The background is currently only available in Chinese

**Comment by vanloc0301** [comment]
I using English is the main language. 

I think you need to add a version README-EN.md.

Can many users on Github will interest your repo.

I very excited with your Repo.

Awesome.

**Comment by fancyecommerce** [comment]
@vanloc0301  http://www.fecshop.com/doc/fecshop-guide/develop/cn-1.0/guide-fecshop-about-hand-install.html

**Comment by fancyecommerce** [comment]
@vanloc0301  my english is bad
