### ISSUE TITLE
Issues when install Fecshop

### ISSUE THREAD

**Issue by vanloc0301** [fancyecommerce/yii2_fecshop#5]
I have some issues when tried to install **_Fecshop_**  in my Arch.

1. DocRoot.
I tried to run the command: 
```php yii serve```

show errors like:

> Document root "/srv/http/fecshop/console/web" does not exist.

So, I must tried to: 

`php yii serve --port=8888 --docroot="/srv/http/fecshop/appserver/web"`

How to skip this error?

2. this domain is not config in store component

Iin `/srv/http/fecshop/vendor/fancyecommerce/fecshop/services/Store.php` it go to exception at line 113:

```
if(!$init_compelte){
      throw new InvalidValueException('this domain is not config in store component');
}
```

3.  Bootstrap error:

I take a photo error relate with Bootstrap.

![screenshot_2017-04-27_03-53-26](https://cloud.githubusercontent.com/assets/4168981/25456455/20e6b7e4-2afd-11e7-98cc-68255337e1c7.png)

4. Another error you will see in this photo. I think I lost any config in your document. I tried. But not a success.

See this photo:
![screenshot_2017-04-27_03-56-48](https://cloud.githubusercontent.com/assets/4168981/25456653/b6e25e6a-2afd-11e7-9ffb-cd7e4ecd1c45.png)

Finally, I tried to using Google Translate to translate your document, but I don't know all. So, I have some error when setup on my PC.

Thanks.

**Comment by fancyecommerce** [comment]
only develop  appfront and appadmin
    @appfront/web/index.php
    @appadmin/web/index.php
other @app is disabled,  The other entrance is not developed

**Comment by vanloc0301** [comment]
Dear @fancyecommerce . 

I tried with command:

`php yii serve --port=8888 --docroot="/srv/http/fecshop/appfront/web"`

with same all error.

I have 4 problems when installing Fecshop.

Can you read again my issues? 

Thanks.
