### ISSUE TITLE
可以提供一个 Docker 部署方式吗？

### ISSUE THREAD

**Issue by cshanxiao** [fancyecommerce/yii2_fecshop#6]
可以提供一个 Docker 部署方式吗？
安装步骤实在太复杂，已把大批用户挡在门外；

**Comment by fancyecommerce** [comment]
目前没有docker，不过有vagrant的安装方式， [vagrant 安装fecshop](http://www.fecshop.com/doc/fecshop-guide/develop/cn-1.0/guide-fecshop-about-vagrantinstall.html)
安装其实不复杂，fecshop是基于yii2的安装，在这个基础上，在安装mongodb 和redis就可以了。
电商本身就是一个复杂的东西，有很多配置项，这个是无法避免的，而fecshop更多的是以实战的方式展开的，在第一次安装的配置方面，会感觉比较繁多，因此，安装要有点耐心。
等apphtml5  手机web部分做完，我会出个安装视频。
fecshop是有一定技术情怀在里面，目前我一个人开发，2010年开始一直在跨境外贸B2C圈子里面混迹。
多点耐心安装。

**Comment by fancyecommerce** [comment]
fecshop的定位，不是小白用户，而是程序员。
纯小白安装还是不行的。
对于像magento zencart 小白即使安装起来，在实战过程中，没有程序员的情况下上线一个网站，几乎是不可能的。
因此，纯小白，不依赖程序员自己完全搞定，无论哪个开源系统，几乎都是不可能的。

**Comment by cshanxiao** [comment]
当然不是纯小白了，说实话，我是工作了很多年的程序，但看到那十几个手动安装步骤也难免退缩了一下，普通运维也很难搞定这部署，产品需要面向大众才能发挥价值，能自动完成的就应该让产品自己完成；

**Comment by fancyecommerce** [comment]
那你可以选择不玩，没强制你

**Comment by fancyecommerce** [comment]
工作多年的程序，几个小时就搞定，都说xx还不如回家抱孩子，抱孩子就很容易吗？
就一个安装，这都惧怕，还过来玩个甚？fecshop就是这个样子，你可以选择其他产品。

**Comment by cshanxiao** [comment]
抱歉，我只是建议一下，无意触犯，请谅解，希望你能做的更好；

**Comment by fancyecommerce** [comment]
没事，我也是实话实说，没有任何感情色彩
